theme: jekyll-theme-tactile
title: Chase Stauts
description: Computer Science undergraduate at Boise State University
url: https://github.com/ChaseStauts
url: https://www.linkedin.com/in/chasestauts/
