theme: jekyll-theme-tactile
title: Chase Stauts
description: Computer Science undergraduate at Boise State University
description: [GitHub]https://github.com/ChaseStauts
description: [LinkedIn] https://www.linkedin.com/in/chasestauts/
