theme: jekyll-theme-tactile
title: Welcome to Chase Stauts's homepage!
description: Computer Science undergraduate at Boise State University
description: Interests: Artificial Intelligence, Cryptography, Firmware, Game Development
