theme: jekyll-theme-tactile
title: Chase Stauts
description: Computer Science undergraduate at Boise State University [GitHub](https://github.com/ChaseStauts) [LinkedIn](https://www.linkedin.com/in/chasestauts)
