theme: jekyll-theme-tactile
title: Chase Stauts
<img src="https://github.com/ChaseStauts/chasestauts.github.io/blob/master/Senior%20pic.jpg">
description: Computer Science undergraduate at Boise State University
