theme: jekyll-theme-tactile
title: Chase Stauts
<img src="https://raw.githubusercontent.com/ChaseStauts/chasestauts.github.io/master/Senior%20pic.png">
description: Computer Science undergraduate at Boise State University
