theme: jekyll-theme-tactile
title: Chase Stauts
description: Computer Science undergraduate at Boise State University
GitHub: [GitHub](https://github.com/ChaseStauts)
LinkedIn: [LinkedIn](https://www.linkedin.com/in/chasestauts)
